[13-Jul-2024 17:24:29 UTC] PDOException: SQLSTATE[HY000] [1044] Access denied for user 'dondurmacci'@'localhost' to database 'dondurmacci' in /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php on line 79 #0 /home/cej5vsm359bz/public_html/web/core/modules/mysql/src/Driver/Database/mysql/Connection.php(179): PDO->__construct()
#1 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Core/Database/Database.php(464): Drupal\mysql\Driver\Database\mysql\Connection::open()
#2 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Core/Database/Database.php(195): Drupal\Core\Database\Database::openConnection()
#3 [internal function]: Drupal\Core\Database\Database::getConnection()
#4 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array()
#5 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Component/DependencyInjection/Container.php(177): Drupal\Component\DependencyInjection\PhpArrayContainer->createService()
#6 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(219): Drupal\Component\DependencyInjection\Container->get()
#7 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\Component\DependencyInjection\PhpArrayContainer->resolveServicesAndParameters()
#8 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Component/DependencyInjection/Container.php(177): Drupal\Component\DependencyInjection\PhpArrayContainer->createService()
#9 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Core/DrupalKernel.php(554): Drupal\Component\DependencyInjection\Container->get()
#10 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Core/DrupalKernel.php(928): Drupal\Core\DrupalKernel->getCachedContainerDefinition()
#11 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Core/DrupalKernel.php(494): Drupal\Core\DrupalKernel->initializeContainer()
#12 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Core/DrupalKernel.php(702): Drupal\Core\DrupalKernel->boot()
#13 /home/cej5vsm359bz/public_html/web/index.php(19): Drupal\Core\DrupalKernel->handle()
#14 {main}
[13-Jul-2024 17:24:37 UTC] PDOException: SQLSTATE[HY000] [1044] Access denied for user 'dondurmacci'@'localhost' to database 'dondurmacci' in /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php on line 79 #0 /home/cej5vsm359bz/public_html/web/core/modules/mysql/src/Driver/Database/mysql/Connection.php(179): PDO->__construct()
#1 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Core/Database/Database.php(464): Drupal\mysql\Driver\Database\mysql\Connection::open()
#2 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Core/Database/Database.php(195): Drupal\Core\Database\Database::openConnection()
#3 [internal function]: Drupal\Core\Database\Database::getConnection()
#4 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array()
#5 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Component/DependencyInjection/Container.php(177): Drupal\Component\DependencyInjection\PhpArrayContainer->createService()
#6 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(219): Drupal\Component\DependencyInjection\Container->get()
#7 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\Component\DependencyInjection\PhpArrayContainer->resolveServicesAndParameters()
#8 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Component/DependencyInjection/Container.php(177): Drupal\Component\DependencyInjection\PhpArrayContainer->createService()
#9 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Core/DrupalKernel.php(554): Drupal\Component\DependencyInjection\Container->get()
#10 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Core/DrupalKernel.php(928): Drupal\Core\DrupalKernel->getCachedContainerDefinition()
#11 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Core/DrupalKernel.php(494): Drupal\Core\DrupalKernel->initializeContainer()
#12 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Core/DrupalKernel.php(702): Drupal\Core\DrupalKernel->boot()
#13 /home/cej5vsm359bz/public_html/web/index.php(19): Drupal\Core\DrupalKernel->handle()
#14 {main}
[13-Jul-2024 17:24:49 UTC] PDOException: SQLSTATE[HY000] [1044] Access denied for user 'dondurmacci'@'localhost' to database 'dondurmacci' in /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php on line 79 #0 /home/cej5vsm359bz/public_html/web/core/modules/mysql/src/Driver/Database/mysql/Connection.php(179): PDO->__construct()
#1 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Core/Database/Database.php(464): Drupal\mysql\Driver\Database\mysql\Connection::open()
#2 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Core/Database/Database.php(195): Drupal\Core\Database\Database::openConnection()
#3 [internal function]: Drupal\Core\Database\Database::getConnection()
#4 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array()
#5 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Component/DependencyInjection/Container.php(177): Drupal\Component\DependencyInjection\PhpArrayContainer->createService()
#6 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(219): Drupal\Component\DependencyInjection\Container->get()
#7 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\Component\DependencyInjection\PhpArrayContainer->resolveServicesAndParameters()
#8 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Component/DependencyInjection/Container.php(177): Drupal\Component\DependencyInjection\PhpArrayContainer->createService()
#9 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Core/DrupalKernel.php(554): Drupal\Component\DependencyInjection\Container->get()
#10 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Core/DrupalKernel.php(928): Drupal\Core\DrupalKernel->getCachedContainerDefinition()
#11 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Core/DrupalKernel.php(494): Drupal\Core\DrupalKernel->initializeContainer()
#12 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Core/DrupalKernel.php(702): Drupal\Core\DrupalKernel->boot()
#13 /home/cej5vsm359bz/public_html/web/index.php(19): Drupal\Core\DrupalKernel->handle()
#14 {main}
[13-Jul-2024 17:26:04 UTC] PDOException: SQLSTATE[HY000] [1044] Access denied for user 'dondurmacci'@'localhost' to database 'dondurmacci' in /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php on line 79 #0 /home/cej5vsm359bz/public_html/web/core/modules/mysql/src/Driver/Database/mysql/Connection.php(179): PDO->__construct()
#1 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Core/Database/Database.php(464): Drupal\mysql\Driver\Database\mysql\Connection::open()
#2 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Core/Database/Database.php(195): Drupal\Core\Database\Database::openConnection()
#3 [internal function]: Drupal\Core\Database\Database::getConnection()
#4 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array()
#5 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Component/DependencyInjection/Container.php(177): Drupal\Component\DependencyInjection\PhpArrayContainer->createService()
#6 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(219): Drupal\Component\DependencyInjection\Container->get()
#7 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\Component\DependencyInjection\PhpArrayContainer->resolveServicesAndParameters()
#8 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Component/DependencyInjection/Container.php(177): Drupal\Component\DependencyInjection\PhpArrayContainer->createService()
#9 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Core/DrupalKernel.php(554): Drupal\Component\DependencyInjection\Container->get()
#10 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Core/DrupalKernel.php(928): Drupal\Core\DrupalKernel->getCachedContainerDefinition()
#11 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Core/DrupalKernel.php(494): Drupal\Core\DrupalKernel->initializeContainer()
#12 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Core/DrupalKernel.php(702): Drupal\Core\DrupalKernel->boot()
#13 /home/cej5vsm359bz/public_html/web/index.php(19): Drupal\Core\DrupalKernel->handle()
#14 {main}
[13-Jul-2024 17:26:23 UTC] PDOException: SQLSTATE[HY000] [1044] Access denied for user 'dondurmacci'@'localhost' to database 'dondurmacci' in /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php on line 79 #0 /home/cej5vsm359bz/public_html/web/core/modules/mysql/src/Driver/Database/mysql/Connection.php(179): PDO->__construct()
#1 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Core/Database/Database.php(464): Drupal\mysql\Driver\Database\mysql\Connection::open()
#2 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Core/Database/Database.php(195): Drupal\Core\Database\Database::openConnection()
#3 [internal function]: Drupal\Core\Database\Database::getConnection()
#4 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array()
#5 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Component/DependencyInjection/Container.php(177): Drupal\Component\DependencyInjection\PhpArrayContainer->createService()
#6 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(219): Drupal\Component\DependencyInjection\Container->get()
#7 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\Component\DependencyInjection\PhpArrayContainer->resolveServicesAndParameters()
#8 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Component/DependencyInjection/Container.php(177): Drupal\Component\DependencyInjection\PhpArrayContainer->createService()
#9 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Core/DrupalKernel.php(554): Drupal\Component\DependencyInjection\Container->get()
#10 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Core/DrupalKernel.php(928): Drupal\Core\DrupalKernel->getCachedContainerDefinition()
#11 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Core/DrupalKernel.php(494): Drupal\Core\DrupalKernel->initializeContainer()
#12 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Core/DrupalKernel.php(702): Drupal\Core\DrupalKernel->boot()
#13 /home/cej5vsm359bz/public_html/web/index.php(19): Drupal\Core\DrupalKernel->handle()
#14 {main}
[13-Jul-2024 17:27:53 UTC] PDOException: SQLSTATE[HY000] [1044] Access denied for user 'dondurmacci'@'localhost' to database 'dondurmacci' in /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php on line 79 #0 /home/cej5vsm359bz/public_html/web/core/modules/mysql/src/Driver/Database/mysql/Connection.php(179): PDO->__construct()
#1 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Core/Database/Database.php(464): Drupal\mysql\Driver\Database\mysql\Connection::open()
#2 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Core/Database/Database.php(195): Drupal\Core\Database\Database::openConnection()
#3 [internal function]: Drupal\Core\Database\Database::getConnection()
#4 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array()
#5 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Component/DependencyInjection/Container.php(177): Drupal\Component\DependencyInjection\PhpArrayContainer->createService()
#6 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(219): Drupal\Component\DependencyInjection\Container->get()
#7 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\Component\DependencyInjection\PhpArrayContainer->resolveServicesAndParameters()
#8 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Component/DependencyInjection/Container.php(177): Drupal\Component\DependencyInjection\PhpArrayContainer->createService()
#9 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Core/DrupalKernel.php(554): Drupal\Component\DependencyInjection\Container->get()
#10 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Core/DrupalKernel.php(928): Drupal\Core\DrupalKernel->getCachedContainerDefinition()
#11 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Core/DrupalKernel.php(494): Drupal\Core\DrupalKernel->initializeContainer()
#12 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Core/DrupalKernel.php(702): Drupal\Core\DrupalKernel->boot()
#13 /home/cej5vsm359bz/public_html/web/index.php(19): Drupal\Core\DrupalKernel->handle()
#14 {main}
[13-Jul-2024 17:27:54 UTC] PDOException: SQLSTATE[HY000] [1044] Access denied for user 'dondurmacci'@'localhost' to database 'dondurmacci' in /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php on line 79 #0 /home/cej5vsm359bz/public_html/web/core/modules/mysql/src/Driver/Database/mysql/Connection.php(179): PDO->__construct()
#1 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Core/Database/Database.php(464): Drupal\mysql\Driver\Database\mysql\Connection::open()
#2 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Core/Database/Database.php(195): Drupal\Core\Database\Database::openConnection()
#3 [internal function]: Drupal\Core\Database\Database::getConnection()
#4 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array()
#5 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Component/DependencyInjection/Container.php(177): Drupal\Component\DependencyInjection\PhpArrayContainer->createService()
#6 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(219): Drupal\Component\DependencyInjection\Container->get()
#7 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\Component\DependencyInjection\PhpArrayContainer->resolveServicesAndParameters()
#8 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Component/DependencyInjection/Container.php(177): Drupal\Component\DependencyInjection\PhpArrayContainer->createService()
#9 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Core/DrupalKernel.php(554): Drupal\Component\DependencyInjection\Container->get()
#10 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Core/DrupalKernel.php(928): Drupal\Core\DrupalKernel->getCachedContainerDefinition()
#11 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Core/DrupalKernel.php(494): Drupal\Core\DrupalKernel->initializeContainer()
#12 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Core/DrupalKernel.php(702): Drupal\Core\DrupalKernel->boot()
#13 /home/cej5vsm359bz/public_html/web/index.php(19): Drupal\Core\DrupalKernel->handle()
#14 {main}
[13-Jul-2024 17:27:55 UTC] PDOException: SQLSTATE[HY000] [1044] Access denied for user 'dondurmacci'@'localhost' to database 'dondurmacci' in /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php on line 79 #0 /home/cej5vsm359bz/public_html/web/core/modules/mysql/src/Driver/Database/mysql/Connection.php(179): PDO->__construct()
#1 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Core/Database/Database.php(464): Drupal\mysql\Driver\Database\mysql\Connection::open()
#2 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Core/Database/Database.php(195): Drupal\Core\Database\Database::openConnection()
#3 [internal function]: Drupal\Core\Database\Database::getConnection()
#4 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array()
#5 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Component/DependencyInjection/Container.php(177): Drupal\Component\DependencyInjection\PhpArrayContainer->createService()
#6 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(219): Drupal\Component\DependencyInjection\Container->get()
#7 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\Component\DependencyInjection\PhpArrayContainer->resolveServicesAndParameters()
#8 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Component/DependencyInjection/Container.php(177): Drupal\Component\DependencyInjection\PhpArrayContainer->createService()
#9 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Core/DrupalKernel.php(554): Drupal\Component\DependencyInjection\Container->get()
#10 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Core/DrupalKernel.php(928): Drupal\Core\DrupalKernel->getCachedContainerDefinition()
#11 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Core/DrupalKernel.php(494): Drupal\Core\DrupalKernel->initializeContainer()
#12 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Core/DrupalKernel.php(702): Drupal\Core\DrupalKernel->boot()
#13 /home/cej5vsm359bz/public_html/web/index.php(19): Drupal\Core\DrupalKernel->handle()
#14 {main}
[13-Jul-2024 17:27:55 UTC] PDOException: SQLSTATE[HY000] [1044] Access denied for user 'dondurmacci'@'localhost' to database 'dondurmacci' in /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php on line 79 #0 /home/cej5vsm359bz/public_html/web/core/modules/mysql/src/Driver/Database/mysql/Connection.php(179): PDO->__construct()
#1 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Core/Database/Database.php(464): Drupal\mysql\Driver\Database\mysql\Connection::open()
#2 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Core/Database/Database.php(195): Drupal\Core\Database\Database::openConnection()
#3 [internal function]: Drupal\Core\Database\Database::getConnection()
#4 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array()
#5 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Component/DependencyInjection/Container.php(177): Drupal\Component\DependencyInjection\PhpArrayContainer->createService()
#6 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(219): Drupal\Component\DependencyInjection\Container->get()
#7 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\Component\DependencyInjection\PhpArrayContainer->resolveServicesAndParameters()
#8 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Component/DependencyInjection/Container.php(177): Drupal\Component\DependencyInjection\PhpArrayContainer->createService()
#9 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Core/DrupalKernel.php(554): Drupal\Component\DependencyInjection\Container->get()
#10 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Core/DrupalKernel.php(928): Drupal\Core\DrupalKernel->getCachedContainerDefinition()
#11 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Core/DrupalKernel.php(494): Drupal\Core\DrupalKernel->initializeContainer()
#12 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Core/DrupalKernel.php(702): Drupal\Core\DrupalKernel->boot()
#13 /home/cej5vsm359bz/public_html/web/index.php(19): Drupal\Core\DrupalKernel->handle()
#14 {main}
[13-Jul-2024 17:27:55 UTC] PDOException: SQLSTATE[HY000] [1044] Access denied for user 'dondurmacci'@'localhost' to database 'dondurmacci' in /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php on line 79 #0 /home/cej5vsm359bz/public_html/web/core/modules/mysql/src/Driver/Database/mysql/Connection.php(179): PDO->__construct()
#1 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Core/Database/Database.php(464): Drupal\mysql\Driver\Database\mysql\Connection::open()
#2 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Core/Database/Database.php(195): Drupal\Core\Database\Database::openConnection()
#3 [internal function]: Drupal\Core\Database\Database::getConnection()
#4 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array()
#5 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Component/DependencyInjection/Container.php(177): Drupal\Component\DependencyInjection\PhpArrayContainer->createService()
#6 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(219): Drupal\Component\DependencyInjection\Container->get()
#7 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\Component\DependencyInjection\PhpArrayContainer->resolveServicesAndParameters()
#8 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Component/DependencyInjection/Container.php(177): Drupal\Component\DependencyInjection\PhpArrayContainer->createService()
#9 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Core/DrupalKernel.php(554): Drupal\Component\DependencyInjection\Container->get()
#10 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Core/DrupalKernel.php(928): Drupal\Core\DrupalKernel->getCachedContainerDefinition()
#11 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Core/DrupalKernel.php(494): Drupal\Core\DrupalKernel->initializeContainer()
#12 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Core/DrupalKernel.php(702): Drupal\Core\DrupalKernel->boot()
#13 /home/cej5vsm359bz/public_html/web/index.php(19): Drupal\Core\DrupalKernel->handle()
#14 {main}
[13-Jul-2024 17:27:56 UTC] PDOException: SQLSTATE[HY000] [1044] Access denied for user 'dondurmacci'@'localhost' to database 'dondurmacci' in /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php on line 79 #0 /home/cej5vsm359bz/public_html/web/core/modules/mysql/src/Driver/Database/mysql/Connection.php(179): PDO->__construct()
#1 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Core/Database/Database.php(464): Drupal\mysql\Driver\Database\mysql\Connection::open()
#2 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Core/Database/Database.php(195): Drupal\Core\Database\Database::openConnection()
#3 [internal function]: Drupal\Core\Database\Database::getConnection()
#4 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array()
#5 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Component/DependencyInjection/Container.php(177): Drupal\Component\DependencyInjection\PhpArrayContainer->createService()
#6 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(219): Drupal\Component\DependencyInjection\Container->get()
#7 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\Component\DependencyInjection\PhpArrayContainer->resolveServicesAndParameters()
#8 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Component/DependencyInjection/Container.php(177): Drupal\Component\DependencyInjection\PhpArrayContainer->createService()
#9 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Core/DrupalKernel.php(554): Drupal\Component\DependencyInjection\Container->get()
#10 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Core/DrupalKernel.php(928): Drupal\Core\DrupalKernel->getCachedContainerDefinition()
#11 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Core/DrupalKernel.php(494): Drupal\Core\DrupalKernel->initializeContainer()
#12 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Core/DrupalKernel.php(702): Drupal\Core\DrupalKernel->boot()
#13 /home/cej5vsm359bz/public_html/web/index.php(19): Drupal\Core\DrupalKernel->handle()
#14 {main}
[13-Jul-2024 17:28:02 UTC] PDOException: SQLSTATE[HY000] [1044] Access denied for user 'dondurmacci'@'localhost' to database 'dondurmacci' in /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php on line 79 #0 /home/cej5vsm359bz/public_html/web/core/modules/mysql/src/Driver/Database/mysql/Connection.php(179): PDO->__construct()
#1 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Core/Database/Database.php(464): Drupal\mysql\Driver\Database\mysql\Connection::open()
#2 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Core/Database/Database.php(195): Drupal\Core\Database\Database::openConnection()
#3 [internal function]: Drupal\Core\Database\Database::getConnection()
#4 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array()
#5 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Component/DependencyInjection/Container.php(177): Drupal\Component\DependencyInjection\PhpArrayContainer->createService()
#6 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(219): Drupal\Component\DependencyInjection\Container->get()
#7 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\Component\DependencyInjection\PhpArrayContainer->resolveServicesAndParameters()
#8 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Component/DependencyInjection/Container.php(177): Drupal\Component\DependencyInjection\PhpArrayContainer->createService()
#9 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Core/DrupalKernel.php(554): Drupal\Component\DependencyInjection\Container->get()
#10 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Core/DrupalKernel.php(928): Drupal\Core\DrupalKernel->getCachedContainerDefinition()
#11 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Core/DrupalKernel.php(494): Drupal\Core\DrupalKernel->initializeContainer()
#12 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Core/DrupalKernel.php(702): Drupal\Core\DrupalKernel->boot()
#13 /home/cej5vsm359bz/public_html/web/index.php(19): Drupal\Core\DrupalKernel->handle()
#14 {main}
[13-Jul-2024 17:28:11 UTC] PDOException: SQLSTATE[HY000] [1044] Access denied for user 'dondurmacci'@'localhost' to database 'dondurmacci' in /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php on line 79 #0 /home/cej5vsm359bz/public_html/web/core/modules/mysql/src/Driver/Database/mysql/Connection.php(179): PDO->__construct()
#1 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Core/Database/Database.php(464): Drupal\mysql\Driver\Database\mysql\Connection::open()
#2 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Core/Database/Database.php(195): Drupal\Core\Database\Database::openConnection()
#3 [internal function]: Drupal\Core\Database\Database::getConnection()
#4 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array()
#5 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Component/DependencyInjection/Container.php(177): Drupal\Component\DependencyInjection\PhpArrayContainer->createService()
#6 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(219): Drupal\Component\DependencyInjection\Container->get()
#7 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\Component\DependencyInjection\PhpArrayContainer->resolveServicesAndParameters()
#8 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Component/DependencyInjection/Container.php(177): Drupal\Component\DependencyInjection\PhpArrayContainer->createService()
#9 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Core/DrupalKernel.php(554): Drupal\Component\DependencyInjection\Container->get()
#10 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Core/DrupalKernel.php(928): Drupal\Core\DrupalKernel->getCachedContainerDefinition()
#11 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Core/DrupalKernel.php(494): Drupal\Core\DrupalKernel->initializeContainer()
#12 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Core/DrupalKernel.php(702): Drupal\Core\DrupalKernel->boot()
#13 /home/cej5vsm359bz/public_html/web/index.php(19): Drupal\Core\DrupalKernel->handle()
#14 {main}
[13-Jul-2024 17:28:11 UTC] PDOException: SQLSTATE[HY000] [1044] Access denied for user 'dondurmacci'@'localhost' to database 'dondurmacci' in /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php on line 79 #0 /home/cej5vsm359bz/public_html/web/core/modules/mysql/src/Driver/Database/mysql/Connection.php(179): PDO->__construct()
#1 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Core/Database/Database.php(464): Drupal\mysql\Driver\Database\mysql\Connection::open()
#2 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Core/Database/Database.php(195): Drupal\Core\Database\Database::openConnection()
#3 [internal function]: Drupal\Core\Database\Database::getConnection()
#4 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array()
#5 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Component/DependencyInjection/Container.php(177): Drupal\Component\DependencyInjection\PhpArrayContainer->createService()
#6 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(219): Drupal\Component\DependencyInjection\Container->get()
#7 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\Component\DependencyInjection\PhpArrayContainer->resolveServicesAndParameters()
#8 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Component/DependencyInjection/Container.php(177): Drupal\Component\DependencyInjection\PhpArrayContainer->createService()
#9 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Core/DrupalKernel.php(554): Drupal\Component\DependencyInjection\Container->get()
#10 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Core/DrupalKernel.php(928): Drupal\Core\DrupalKernel->getCachedContainerDefinition()
#11 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Core/DrupalKernel.php(494): Drupal\Core\DrupalKernel->initializeContainer()
#12 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Core/DrupalKernel.php(702): Drupal\Core\DrupalKernel->boot()
#13 /home/cej5vsm359bz/public_html/web/index.php(19): Drupal\Core\DrupalKernel->handle()
#14 {main}
[13-Jul-2024 17:28:12 UTC] PDOException: SQLSTATE[HY000] [1044] Access denied for user 'dondurmacci'@'localhost' to database 'dondurmacci' in /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php on line 79 #0 /home/cej5vsm359bz/public_html/web/core/modules/mysql/src/Driver/Database/mysql/Connection.php(179): PDO->__construct()
#1 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Core/Database/Database.php(464): Drupal\mysql\Driver\Database\mysql\Connection::open()
#2 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Core/Database/Database.php(195): Drupal\Core\Database\Database::openConnection()
#3 [internal function]: Drupal\Core\Database\Database::getConnection()
#4 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array()
#5 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Component/DependencyInjection/Container.php(177): Drupal\Component\DependencyInjection\PhpArrayContainer->createService()
#6 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(219): Drupal\Component\DependencyInjection\Container->get()
#7 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\Component\DependencyInjection\PhpArrayContainer->resolveServicesAndParameters()
#8 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Component/DependencyInjection/Container.php(177): Drupal\Component\DependencyInjection\PhpArrayContainer->createService()
#9 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Core/DrupalKernel.php(554): Drupal\Component\DependencyInjection\Container->get()
#10 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Core/DrupalKernel.php(928): Drupal\Core\DrupalKernel->getCachedContainerDefinition()
#11 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Core/DrupalKernel.php(494): Drupal\Core\DrupalKernel->initializeContainer()
#12 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Core/DrupalKernel.php(702): Drupal\Core\DrupalKernel->boot()
#13 /home/cej5vsm359bz/public_html/web/index.php(19): Drupal\Core\DrupalKernel->handle()
#14 {main}
[13-Jul-2024 17:28:21 UTC] PDOException: SQLSTATE[HY000] [1044] Access denied for user 'dondurmacci'@'localhost' to database 'dondurmacci' in /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php on line 79 #0 /home/cej5vsm359bz/public_html/web/core/modules/mysql/src/Driver/Database/mysql/Connection.php(179): PDO->__construct()
#1 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Core/Database/Database.php(464): Drupal\mysql\Driver\Database\mysql\Connection::open()
#2 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Core/Database/Database.php(195): Drupal\Core\Database\Database::openConnection()
#3 [internal function]: Drupal\Core\Database\Database::getConnection()
#4 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array()
#5 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Component/DependencyInjection/Container.php(177): Drupal\Component\DependencyInjection\PhpArrayContainer->createService()
#6 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(219): Drupal\Component\DependencyInjection\Container->get()
#7 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\Component\DependencyInjection\PhpArrayContainer->resolveServicesAndParameters()
#8 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Component/DependencyInjection/Container.php(177): Drupal\Component\DependencyInjection\PhpArrayContainer->createService()
#9 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Core/DrupalKernel.php(554): Drupal\Component\DependencyInjection\Container->get()
#10 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Core/DrupalKernel.php(928): Drupal\Core\DrupalKernel->getCachedContainerDefinition()
#11 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Core/DrupalKernel.php(494): Drupal\Core\DrupalKernel->initializeContainer()
#12 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Core/DrupalKernel.php(702): Drupal\Core\DrupalKernel->boot()
#13 /home/cej5vsm359bz/public_html/web/index.php(19): Drupal\Core\DrupalKernel->handle()
#14 {main}
[13-Jul-2024 21:24:28 Europe/Istanbul] Uncaught PHP Exception Drupal\Core\Entity\Query\QueryException: "Entity queries must explicitly set whether the query should be access checked or not. See Drupal\Core\Entity\Query\QueryInterface::accessCheck()." at /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Core/Entity/Query/Sql/Query.php line 141
[13-Jul-2024 21:32:21 Europe/Istanbul] Uncaught PHP Exception InvalidArgumentException: "Invalid credit card type "HrWchguL5VAfDsLYrU7L4mvyoH_TXrhz0Cj906if3HEwMwwLisDKmqZ_CQrJZrOI9Zao-lLG"" at /home/cej5vsm359bz/public_html/web/modules/contrib/commerce/modules/payment/src/CreditCard.php line 31
[13-Jul-2024 21:37:44 Europe/Istanbul] Uncaught PHP Exception InvalidArgumentException: "Invalid credit card type "8c4bamy3WV54iLpFfCzZCd7IzjJWWrwU0N9v70c2lWIwM_ixAf72DiB2TBEDl1iaJ3i6z5hK"" at /home/cej5vsm359bz/public_html/web/modules/contrib/commerce/modules/payment/src/CreditCard.php line 31
[13-Jul-2024 21:41:29 Europe/Istanbul] Uncaught PHP Exception InvalidArgumentException: "Invalid credit card type "KEmkDg1MPfXUlYpHPNz37MX9ezgH_309UezUFeTcUkEwM7UqsLl4l89oCi_drtbrM9Scneol"" at /home/cej5vsm359bz/public_html/web/modules/contrib/commerce/modules/payment/src/CreditCard.php line 31
[13-Jul-2024 21:44:34 Europe/Istanbul] Uncaught PHP Exception InvalidArgumentException: "Invalid credit card type "peFfm5yLZdY6W5uHfUqoHOQdACF76PuZN1j0q9onEzMwMyiQx3OWkWqfCliqBjMI1LqDWPlH"" at /home/cej5vsm359bz/public_html/web/modules/contrib/commerce/modules/payment/src/CreditCard.php line 31
[13-Jul-2024 18:47:55 UTC] PHP Fatal error:  Uncaught TypeError: Drupal\iyzipay\Plugin\Commerce\PaymentMethodType\FullCreditCard::__construct(): Argument #1 ($logger_factory) must be of type Drupal\Core\Logger\LoggerChannelFactoryInterface, array given, called in /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Core/Plugin/Factory/ContainerFactory.php on line 25 and defined in /home/cej5vsm359bz/public_html/web/modules/contrib/iyzipay/src/Plugin/Commerce/PaymentMethodType/FullCreditCard.php:36
Stack trace:
#0 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Core/Plugin/Factory/ContainerFactory.php(25): Drupal\iyzipay\Plugin\Commerce\PaymentMethodType\FullCreditCard->__construct()
#1 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Component/Plugin/PluginManagerBase.php(83): Drupal\Core\Plugin\Factory\ContainerFactory->createInstance()
#2 /home/cej5vsm359bz/public_html/web/modules/contrib/entity/src/BundlePlugin/BundlePluginHandler.php(70): Drupal\Component\Plugin\PluginManagerBase->createInstance()
#3 /home/cej5vsm359bz/public_html/web/modules/contrib/entity/entity.module(111): Drupal\entity\BundlePlugin\BundlePluginHandler->getFieldStorageDefinitions()
#4 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Core/Entity/EntityFieldManager.php(592): entity_entity_field_storage_info()
#5 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Core/Extension/ModuleHandler.php(388): Drupal\Core\Entity\EntityFieldManager->Drupal\Core\Entity\{closure}()
#6 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Core/Entity/EntityFieldManager.php(589): Drupal\Core\Extension\ModuleHandler->invokeAllWith()
#7 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Core/Entity/EntityFieldManager.php(466): Drupal\Core\Entity\EntityFieldManager->buildFieldStorageDefinitions()
#8 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Core/Entity/Routing/DefaultHtmlRouteProvider.php(359): Drupal\Core\Entity\EntityFieldManager->getFieldStorageDefinitions()
#9 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Core/Entity/Routing/DefaultHtmlRouteProvider.php(270): Drupal\Core\Entity\Routing\DefaultHtmlRouteProvider->getEntityTypeIdKeyType()
#10 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Core/Entity/Routing/DefaultHtmlRouteProvider.php(90): Drupal\Core\Entity\Routing\DefaultHtmlRouteProvider->getEditFormRoute()
#11 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Core/EventSubscriber/EntityRouteProviderSubscriber.php(47): Drupal\Core\Entity\Routing\DefaultHtmlRouteProvider->getRoutes()
#12 [internal function]: Drupal\Core\EventSubscriber\EntityRouteProviderSubscriber->onDynamicRouteEvent()
#13 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Component/EventDispatcher/ContainerAwareEventDispatcher.php(111): call_user_func()
#14 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Core/Routing/RouteBuilder.php(184): Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher->dispatch()
#15 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Core/ProxyClass/Routing/RouteBuilder.php(83): Drupal\Core\Routing\RouteBuilder->rebuild()
#16 /home/cej5vsm359bz/public_html/web/core/includes/common.inc(485): Drupal\Core\ProxyClass\Routing\RouteBuilder->rebuild()
#17 /home/cej5vsm359bz/public_html/web/core/includes/utility.inc(41): drupal_flush_all_caches()
#18 /home/cej5vsm359bz/public_html/vendor/drush/drush/src/Commands/core/CacheRebuildCommands.php(70): drupal_rebuild()
#19 [internal function]: Drush\Commands\core\CacheRebuildCommands->rebuild()
#20 /home/cej5vsm359bz/public_html/vendor/consolidation/annotated-command/src/CommandProcessor.php(276): call_user_func_array()
#21 /home/cej5vsm359bz/public_html/vendor/consolidation/annotated-command/src/CommandProcessor.php(212): Consolidation\AnnotatedCommand\CommandProcessor->runCommandCallback()
#22 /home/cej5vsm359bz/public_html/vendor/consolidation/annotated-command/src/CommandProcessor.php(175): Consolidation\AnnotatedCommand\CommandProcessor->validateRunAndAlter()
#23 /home/cej5vsm359bz/public_html/vendor/consolidation/annotated-command/src/AnnotatedCommand.php(387): Consolidation\AnnotatedCommand\CommandProcessor->process()
#24 /home/cej5vsm359bz/public_html/vendor/symfony/console/Command/Command.php(326): Consolidation\AnnotatedCommand\AnnotatedCommand->execute()
#25 /home/cej5vsm359bz/public_html/vendor/symfony/console/Application.php(1096): Symfony\Component\Console\Command\Command->run()
#26 /home/cej5vsm359bz/public_html/vendor/symfony/console/Application.php(324): Symfony\Component\Console\Application->doRunCommand()
#27 /home/cej5vsm359bz/public_html/vendor/symfony/console/Application.php(175): Symfony\Component\Console\Application->doRun()
#28 /home/cej5vsm359bz/public_html/vendor/drush/drush/src/Runtime/Runtime.php(110): Symfony\Component\Console\Application->run()
#29 /home/cej5vsm359bz/public_html/vendor/drush/drush/src/Runtime/Runtime.php(40): Drush\Runtime\Runtime->doRun()
#30 /home/cej5vsm359bz/public_html/vendor/drush/drush/drush.php(139): Drush\Runtime\Runtime->run()
#31 /home/cej5vsm359bz/public_html/vendor/drush/drush/drush(4): require('/home/cej5vsm35...')
#32 /home/cej5vsm359bz/public_html/vendor/bin/drush(120): include('/home/cej5vsm35...')
#33 {main}
  thrown in /home/cej5vsm359bz/public_html/web/modules/contrib/iyzipay/src/Plugin/Commerce/PaymentMethodType/FullCreditCard.php on line 36
[13-Jul-2024 18:48:46 UTC] PHP Fatal error:  Uncaught TypeError: Drupal\iyzipay\Plugin\Commerce\PaymentMethodType\FullCreditCard::__construct(): Argument #1 ($logger_factory) must be of type Drupal\Core\Logger\LoggerChannelFactoryInterface, array given, called in /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Core/Plugin/Factory/ContainerFactory.php on line 25 and defined in /home/cej5vsm359bz/public_html/web/modules/contrib/iyzipay/src/Plugin/Commerce/PaymentMethodType/FullCreditCard.php:36
Stack trace:
#0 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Core/Plugin/Factory/ContainerFactory.php(25): Drupal\iyzipay\Plugin\Commerce\PaymentMethodType\FullCreditCard->__construct()
#1 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Component/Plugin/PluginManagerBase.php(83): Drupal\Core\Plugin\Factory\ContainerFactory->createInstance()
#2 /home/cej5vsm359bz/public_html/web/modules/contrib/entity/src/BundlePlugin/BundlePluginHandler.php(70): Drupal\Component\Plugin\PluginManagerBase->createInstance()
#3 /home/cej5vsm359bz/public_html/web/modules/contrib/entity/entity.module(111): Drupal\entity\BundlePlugin\BundlePluginHandler->getFieldStorageDefinitions()
#4 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Core/Entity/EntityFieldManager.php(592): entity_entity_field_storage_info()
#5 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Core/Extension/ModuleHandler.php(388): Drupal\Core\Entity\EntityFieldManager->Drupal\Core\Entity\{closure}()
#6 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Core/Entity/EntityFieldManager.php(589): Drupal\Core\Extension\ModuleHandler->invokeAllWith()
#7 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Core/Entity/EntityFieldManager.php(466): Drupal\Core\Entity\EntityFieldManager->buildFieldStorageDefinitions()
#8 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Core/Entity/Routing/DefaultHtmlRouteProvider.php(359): Drupal\Core\Entity\EntityFieldManager->getFieldStorageDefinitions()
#9 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Core/Entity/Routing/DefaultHtmlRouteProvider.php(270): Drupal\Core\Entity\Routing\DefaultHtmlRouteProvider->getEntityTypeIdKeyType()
#10 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Core/Entity/Routing/DefaultHtmlRouteProvider.php(90): Drupal\Core\Entity\Routing\DefaultHtmlRouteProvider->getEditFormRoute()
#11 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Core/EventSubscriber/EntityRouteProviderSubscriber.php(47): Drupal\Core\Entity\Routing\DefaultHtmlRouteProvider->getRoutes()
#12 [internal function]: Drupal\Core\EventSubscriber\EntityRouteProviderSubscriber->onDynamicRouteEvent()
#13 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Component/EventDispatcher/ContainerAwareEventDispatcher.php(111): call_user_func()
#14 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Core/Routing/RouteBuilder.php(184): Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher->dispatch()
#15 /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Core/ProxyClass/Routing/RouteBuilder.php(83): Drupal\Core\Routing\RouteBuilder->rebuild()
#16 /home/cej5vsm359bz/public_html/web/core/includes/common.inc(485): Drupal\Core\ProxyClass\Routing\RouteBuilder->rebuild()
#17 /home/cej5vsm359bz/public_html/web/core/includes/utility.inc(41): drupal_flush_all_caches()
#18 /home/cej5vsm359bz/public_html/vendor/drush/drush/src/Commands/core/CacheRebuildCommands.php(70): drupal_rebuild()
#19 [internal function]: Drush\Commands\core\CacheRebuildCommands->rebuild()
#20 /home/cej5vsm359bz/public_html/vendor/consolidation/annotated-command/src/CommandProcessor.php(276): call_user_func_array()
#21 /home/cej5vsm359bz/public_html/vendor/consolidation/annotated-command/src/CommandProcessor.php(212): Consolidation\AnnotatedCommand\CommandProcessor->runCommandCallback()
#22 /home/cej5vsm359bz/public_html/vendor/consolidation/annotated-command/src/CommandProcessor.php(175): Consolidation\AnnotatedCommand\CommandProcessor->validateRunAndAlter()
#23 /home/cej5vsm359bz/public_html/vendor/consolidation/annotated-command/src/AnnotatedCommand.php(387): Consolidation\AnnotatedCommand\CommandProcessor->process()
#24 /home/cej5vsm359bz/public_html/vendor/symfony/console/Command/Command.php(326): Consolidation\AnnotatedCommand\AnnotatedCommand->execute()
#25 /home/cej5vsm359bz/public_html/vendor/symfony/console/Application.php(1096): Symfony\Component\Console\Command\Command->run()
#26 /home/cej5vsm359bz/public_html/vendor/symfony/console/Application.php(324): Symfony\Component\Console\Application->doRunCommand()
#27 /home/cej5vsm359bz/public_html/vendor/symfony/console/Application.php(175): Symfony\Component\Console\Application->doRun()
#28 /home/cej5vsm359bz/public_html/vendor/drush/drush/src/Runtime/Runtime.php(110): Symfony\Component\Console\Application->run()
#29 /home/cej5vsm359bz/public_html/vendor/drush/drush/src/Runtime/Runtime.php(40): Drush\Runtime\Runtime->doRun()
#30 /home/cej5vsm359bz/public_html/vendor/drush/drush/drush.php(139): Drush\Runtime\Runtime->run()
#31 /home/cej5vsm359bz/public_html/vendor/drush/drush/drush(4): require('/home/cej5vsm35...')
#32 /home/cej5vsm359bz/public_html/vendor/bin/drush(120): include('/home/cej5vsm35...')
#33 {main}
  thrown in /home/cej5vsm359bz/public_html/web/modules/contrib/iyzipay/src/Plugin/Commerce/PaymentMethodType/FullCreditCard.php on line 36
[13-Jul-2024 21:48:55 Europe/Istanbul] Uncaught PHP Exception TypeError: "Drupal\iyzipay\Plugin\Commerce\PaymentMethodType\FullCreditCard::__construct(): Argument #1 ($logger_factory) must be of type Drupal\Core\Logger\LoggerChannelFactoryInterface, array given, called in /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Core/Plugin/Factory/ContainerFactory.php on line 25" at /home/cej5vsm359bz/public_html/web/modules/contrib/iyzipay/src/Plugin/Commerce/PaymentMethodType/FullCreditCard.php line 36
[13-Jul-2024 21:49:00 Europe/Istanbul] Uncaught PHP Exception TypeError: "Drupal\iyzipay\Plugin\Commerce\PaymentMethodType\FullCreditCard::__construct(): Argument #1 ($logger_factory) must be of type Drupal\Core\Logger\LoggerChannelFactoryInterface, array given, called in /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Core/Plugin/Factory/ContainerFactory.php on line 25" at /home/cej5vsm359bz/public_html/web/modules/contrib/iyzipay/src/Plugin/Commerce/PaymentMethodType/FullCreditCard.php line 36
[13-Jul-2024 21:52:08 Europe/Istanbul] Uncaught PHP Exception InvalidArgumentException: "Invalid credit card type "DPCnZiad2kUGz2KgzufwFRufIhqRmIOlpTTQa0QT0wYwM80gw5_RJDIWZCOpYzJQynvnITx7"" at /home/cej5vsm359bz/public_html/web/modules/contrib/commerce/modules/payment/src/CreditCard.php line 31
[13-Jul-2024 21:58:56 Europe/Istanbul] Uncaught PHP Exception Drupal\Core\Entity\Query\QueryException: "Entity queries must explicitly set whether the query should be access checked or not. See Drupal\Core\Entity\Query\QueryInterface::accessCheck()." at /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Core/Entity/Query/Sql/Query.php line 141
[13-Jul-2024 22:05:04 Europe/Istanbul] Uncaught PHP Exception InvalidArgumentException: "Invalid credit card type "yGlKt3ZIyh9n0n5A-RJWV5Tt13YmkDuQC72TqAdymcswM23bCToZJi4TyeTyC3RI9sVpHhj1"" at /home/cej5vsm359bz/public_html/web/modules/contrib/commerce/modules/payment/src/CreditCard.php line 31
[13-Jul-2024 22:25:03 Europe/Istanbul] Uncaught PHP Exception InvalidArgumentException: "Invalid credit card type "gX3URaUhYeR-eMcQeQkIc1rohKTc-aT5tOhPOh0cT_QwM5xibFAlm-vOdWtXqrA21TmtnZA7"" at /home/cej5vsm359bz/public_html/web/modules/contrib/commerce/modules/payment/src/CreditCard.php line 31
[13-Jul-2024 22:40:16 Europe/Istanbul] Uncaught PHP Exception Drupal\Core\Entity\Query\QueryException: "Entity queries must explicitly set whether the query should be access checked or not. See Drupal\Core\Entity\Query\QueryInterface::accessCheck()." at /home/cej5vsm359bz/public_html/web/core/lib/Drupal/Core/Entity/Query/Sql/Query.php line 141
